# This is a basic workflow to help you get started with Actions

name: CI-Scheduled-Job

# Controls when the action will run. Triggers the workflow on push or pull request
# Controls when the action will run. 
on:
  schedule:
    # daily midnight build
    - cron: '0 4 * * *'
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 12
        uses: actions/setup-node@v1
      - run: npm install
      - run: npm run build --if-present
      - run: npm test
